site_name: Hyper-Skin Challenge
site_url: https://uoft-hyperskin.github.io 
site_author: pc-ng

nav:
  - Home: index.md
  - Participate: participate.md
  # - Dataset: dataset.md
  - Committee: committee.md
  - Contact: contact.md
  # - Leaderboard: leaderboard.md

theme:
  name: mkdocs
  include_sidebar: false
  highlights: true
  hljs_languages:
    - yaml
    - python
    - javascript
  nav_style: dark 

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.arithmatex:
      generic: true

extra_javascript:
  - javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

extra:
  consent:
    title: Cookie consent
    description: >- 
      We use cookies to recognize your repeated visits and preferences, as well
      as to measure the effectiveness of our documentation and whether users
      find what they're searching for. With your consent, you're helping us to
      make our documentation better.

copyright: >
  Copyright &copy; 2023 Hyper-Skin, University of Toronto –
  <a href="#__consent">Change cookie settings</a>